FROM node:18-alpine
WORKDIR /app
#Copy Dependencies
COPY .sequelizerc .sequelizerc
COPY database database
RUN npm install sequelize-cli sequelize pg pg-hstore dotenv --no-cache
#Run Migration
ENTRYPOINT ["npx", "sequelize-cli", "db:migrate"]